CLEAR SCREEN
SET SERVEROUTPUT ON
DECLARE
	CUST_ID BankLoanCust.cId%TYPE;
CURSOR CUST_CUR IS
	SELECT cId,due where due BETWEEN  SYSDATE AND SYSDATE+30;
BEGIN
	FOR REC IN CUST_CUR LOOP
		DBMS_OUTPUT.PUT_LINE('LOAN DUE FOR CUSTOMER ID '||cId)
	END LOOP;
END;
/