CREATE OR REPLACE PROCEDURE TransferFunds(S_ID IN NUMBER,R_ID IN NUMBER,AMT IN NUMBER) IS
	BAL NUMBER;
BEGIN
	SELECT BALANCE INTO BAL FROM Account WHERE AID=S_ID;
	IF BAL<AMT THEN
		RAISE_APPLICATION_ERROR(-20001,'Insufficient Funds');
	END IF;
	
	UPDATE Account SET BALANCE=BALANCE-AMT WHERE AID=S_ID;
	UPDATE Account SET BALANCE=BALANCE+AMT WHERE AID=R_ID;
	
	COMMIT;
END;
/
	
	